/**
 * Produces a compact accessibility-oriented representation derived from the DOM.
 *
 * This is NOT the browser's native Accessibility Tree. It is a DOM-derived
 * accessibility-oriented snapshot. It MUST NOT require chrome.debugger/CDP.
 *
 * Semantics:
 * - accessible names, roles, disabled state and (in)visibility use the W3C
 *   accname / ARIA semantics implemented by `dom-accessibility-api` rather than
 *   hand-rolled approximations.
 * - OPEN shadow roots are traversed so web-component UI is discovered.
 * - CLOSED shadow roots are never bypassed; their contents are simply not seen.
 * - candidates are ranked deterministically by browser/page relevance BEFORE
 *   truncation, then bounded by explicit budgets.
 *
 * Security:
 * - Input values are never serialized. Sensitive fields (password/OTP/card) are
 *   represented only by their role and label/state, never their value. The
 *   sanitizer remains the authoritative data-leak boundary.
 */
import type { AccessibleDOMSnapshot, AccessibleElement, ElementState } from "@guided-web/protocol";
import { computeAccessibleName, getRole, isDisabled, isInaccessible } from "dom-accessibility-api";
import { classifySecretField, shouldExcludeElement, redactSensitiveRuns, redactSensitiveVisibleText } from "./sanitizer";
import { iterElements } from "./traversal";
import {
  orderCandidates,
  applyCharacterBudget,
  DEFAULT_BUDGETS,
  type CandidateAnalysis,
  type BudgetSettings,
} from "./relevance";

export interface ExtractOptions {
  /** Provide a snapshotId for deterministic tests; generated by default. */
  snapshotId?: string;
  /** Hard cap on the number of elements included (defensive). */
  maxElements?: number;
  /** Hard cap on the number of visible-text entries. */
  maxVisibleText?: number;
  /** Hard cap on total serialized characters (rough token budget). */
  maxTotalCharacters?: number;
}

function makeId(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c?.randomUUID) return c.randomUUID();
  return `snap-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

const LANDMARK_ROLES = new Set([
  "main",
  "banner",
  "complementary",
  "contentinfo",
  "form",
  "navigation",
  "region",
  "search",
]);
const PRESENTATIONAL_ROLES = new Set(["presentation", "none"]);
const FORM_FIELD_ROLES = new Set([
  "textbox",
  "checkbox",
  "radio",
  "combobox",
  "searchbox",
  "spinbutton",
  "slider",
  "listbox",
  "switch",
  "option",
]);
const BUTTON_LIKE_ROLES = new Set(["button", "link", "menuitem", "tab"]);

function headingLevel(el: Element): number {
  const tag = el.tagName.toLowerCase();
  const m = /^h([1-6])$/.exec(tag);
  if (m) return Number(m[1]);
  const ariaLevel = el.getAttribute("aria-level");
  if (ariaLevel) {
    const n = Number(ariaLevel);
    if (Number.isInteger(n) && n >= 1 && n <= 6) return n;
  }
  return 0;
}

/**
 * Minimal role fallback for the narrow compatibility gap where
 * `dom-accessibility-api` returns null for `<input type="password">`. Security
 * note: this only supplies a semantic role (never a value), so it never
 * introduces a data-leak path; the sanitizer remains authoritative.
 */
function fallbackRole(el: Element): string | null {
  const tag = el.tagName.toLowerCase();
  if (el instanceof HTMLInputElement) {
    return "textbox";
  }
  if (tag === "select") return "combobox";
  if (tag === "textarea") return "textbox";
  if (tag === "button") return "button";
  if (tag === "a" && el.hasAttribute("href")) return "link";
  return null;
}

function effectiveRole(el: Element): string | null {
  return getRole(el) ?? fallbackRole(el);
}

function isInteractive(el: Element, role?: string): boolean {
  const tag = el.tagName.toLowerCase();
  if (["input", "select", "textarea", "button"].includes(tag)) return true;
  if (tag === "a" && el.hasAttribute("href")) return true;
  if (el.hasAttribute("contenteditable")) return true;
  if (role && (FORM_FIELD_ROLES.has(role) || BUTTON_LIKE_ROLES.has(role))) return true;
  const tabindex = el.getAttribute("tabindex");
  if (tabindex !== null && tabindex !== "-1") return true;
  return false;
}

function isFormField(el: Element, role?: string): boolean {
  if (role && FORM_FIELD_ROLES.has(role)) return true;
  const tag = el.tagName.toLowerCase();
  return (
    el instanceof HTMLInputElement ||
    el instanceof HTMLSelectElement ||
    el instanceof HTMLTextAreaElement ||
    tag === "input" ||
    tag === "select" ||
    tag === "textarea"
  );
}

function isCandidate(el: Element, role?: string): boolean {
  if (role && !PRESENTATIONAL_ROLES.has(role)) return true;
  const tag = el.tagName.toLowerCase();
  if (["input", "select", "textarea", "button"].includes(tag)) return true;
  if (tag === "a" && el.hasAttribute("href")) return true;
  if (el.hasAttribute("contenteditable")) return true;
  if (headingLevel(el) > 0) return true;
  if (el.hasAttribute("aria-label") || el.hasAttribute("aria-labelledby")) return true;
  return false;
}

function rootActiveElement(el: Element): Element | null {
  const root = el.getRootNode() as Document | ShadowRoot;
  return (root as { activeElement?: Element | null }).activeElement ?? null;
}

function computeState(el: Element): ElementState | undefined {
  const state: ElementState = {};
  const anyEl = el as HTMLElement;

  if (isDisabled(el)) state.disabled = true;

  const ariaChecked = anyEl.getAttribute("aria-checked");
  if (ariaChecked === "true" || ariaChecked === "false" || ariaChecked === "mixed") {
    state.checked = ariaChecked === "true";
  }
  if (el instanceof HTMLInputElement && (el.type === "checkbox" || el.type === "radio")) {
    state.checked = el.checked;
  }

  const ariaExpanded = anyEl.getAttribute("aria-expanded");
  if (ariaExpanded === "true" || ariaExpanded === "false") {
    state.expanded = ariaExpanded === "true";
  }

  const ariaSelected = anyEl.getAttribute("aria-selected");
  if (ariaSelected === "true" || ariaSelected === "false") {
    state.selected = ariaSelected === "true";
  }

  if (el instanceof HTMLInputElement) state.empty = el.value.length === 0;
  else if (el instanceof HTMLTextAreaElement) state.empty = el.value.length === 0;
  else if (el instanceof HTMLSelectElement) state.empty = el.selectedIndex < 0;

  if (rootActiveElement(el) === el) state.focused = true;

  return Object.keys(state).length > 0 ? state : undefined;
}

function analyze(el: Element, domIndex: number, role: string | undefined): CandidateAnalysis {
  const secretKind = classifySecretField(el);
  const accessibleNameRaw = computeAccessibleName(el).trim().slice(0, 160);
  const accessibleName =
    secretKind === "none" ? accessibleNameRaw : redactSensitiveRuns(accessibleNameRaw, secretKind);

  const tag = el.tagName.toLowerCase();
  const lcName = accessibleName.toLowerCase();
  const state = computeState(el);
  const fallbackText = (el.textContent || "").trim().slice(0, 120);

  return {
    domIndex,
    tag,
    role,
    accessibleName,
    interactive: isInteractive(el, role),
    state,
    visible: !isInaccessible(el),
    headingLevel: headingLevel(el),
    isFocused: rootActiveElement(el) === el,
    isAlertOrError:
      role === "alert" || role === "alertdialog" || el.getAttribute("aria-live") === "assertive" || el.getAttribute("aria-invalid") === "true",
    isInDialog:
      role === "dialog" || role === "alertdialog" || el.getAttribute("aria-modal") === "true",
    isStateful:
      el.hasAttribute("aria-checked") ||
      el.hasAttribute("aria-expanded") ||
      el.hasAttribute("aria-selected"),
    isLandmark: role ? LANDMARK_ROLES.has(role) : false,
    isNavigation: role === "navigation" || tag === "nav",
    isFooterLike:
      tag === "footer" || role === "contentinfo" || /(^|\b)(legal|privacy|terms|copyright|©|theme)(\b|$)/.test(lcName),
    isFormField: isFormField(el, role),
    dedupeText: accessibleName || fallbackText,
  };
}

function collectCandidates(root: Document | ShadowRoot): CandidateAnalysis[] {
  const out: CandidateAnalysis[] = [];
  let domIndex = 0;
  for (const el of iterElements(root)) {
    const idx = domIndex++;
    if (shouldExcludeElement(el)) continue;
    const role = effectiveRole(el) ?? undefined;
    if (!isCandidate(el, role)) continue;
    if (isInaccessible(el)) continue;
    out.push(analyze(el, idx, role));
  }
  return out;
}

const VISIBLE_TEXT_SELECTORS = new Set([
  "h1",
  "h2",
  "h3",
  "h4",
  "p",
  "li",
  "label",
  "summary",
  "figcaption",
  "dt",
  "dd",
  "caption",
]);

function collectVisibleText(root: Document | ShadowRoot, maxVisibleText: number): string[] {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const el of iterElements(root)) {
    if (shouldExcludeElement(el)) continue;
    if (isInaccessible(el)) continue;
    if (!VISIBLE_TEXT_SELECTORS.has(el.tagName.toLowerCase())) continue;
    const text = redactSensitiveVisibleText((el.textContent || "").trim());
    if (!text || text.length > 300) continue;
    if (seen.has(text)) continue;
    seen.add(text);
    result.push(text);
    if (result.length >= maxVisibleText) return result;
  }
  return result;
}

/**
 * Build a single-document AccessibleDOMSnapshot from a Document or ShadowRoot.
 *
 * @param root the current document context (top-level or a frame's document).
 */
export function extractAccessibleDOMSnapshot(
  root: Document | ShadowRoot,
  options: ExtractOptions = {},
): AccessibleDOMSnapshot {
  const budgets = { ...DEFAULT_BUDGETS, ...options } as Required<BudgetSettings>;
  const snapshotId = options.snapshotId ?? makeId();

  const doc = root as Document;
  const url = doc.location?.href ?? "";
  let origin = "";
  try {
    origin = new URL(url).origin;
  } catch {
    origin = "";
  }

  const candidates = collectCandidates(root);
  const ordered = orderCandidates(candidates, budgets.maxElements);
  const bounded = applyCharacterBudget(
    ordered,
    budgets.maxTotalCharacters,
    (c) => (c.accessibleName?.length ?? 0) + (c.tag?.length ?? 0) + 8,
  );

  const elements: AccessibleElement[] = bounded.map((r, i) => {
    const a = r.analysis;
    return {
      id: `el-${i}`,
      tag: a.tag,
      role: a.role,
      accessibleName: a.accessibleName,
      interactive: a.interactive,
      state: a.state,
    };
  });

  return {
    schemaVersion: 1,
    snapshotId,
    page: { url, origin, title: doc.title || "" },
    elements,
    visibleText: collectVisibleText(root, budgets.maxVisibleText),
  };
}
