/**
 * Produces a compact accessibility-oriented representation derived from the DOM.
 *
 * This is NOT the browser's native Accessibility Tree.
 * It MUST NOT require chrome.debugger/CDP.
 *
 * Input values are never serialized. Sensitive fields (password/OTP/card) are
 * represented only by their role and label/state, never their value.
 */
import type {
  AccessibleDOMSnapshot,
  AccessibleElement,
  ElementState,
} from "@guided-web/protocol";
import { classifySecretField, shouldExcludeElement, isHidden } from "./sanitizer";

export interface ExtractOptions {
  /** Provide a snapshotId for deterministic tests; generated by default. */
  snapshotId?: string;
  /** Hard cap on the number of elements included (defensive). */
  maxElements?: number;
}

const CANDIDATE_SELECTOR = [
  "input",
  "select",
  "textarea",
  "button",
  "a[href]",
  "[role]",
  "[aria-label]",
  "[aria-labelledby]",
  "[contenteditable]",
  "[tabindex]",
].join(",");

function makeId(): string {
  const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
  if (c?.randomUUID) return c.randomUUID();
  return `snap-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
}

function computeRole(el: Element): string | undefined {
  const explicit = el.getAttribute("role");
  if (explicit) return explicit;
  const tag = el.tagName.toLowerCase();
  if (el instanceof HTMLInputElement) {
    switch ((el.type || "").toLowerCase()) {
      case "checkbox":
        return "checkbox";
      case "radio":
        return "radio";
      case "button":
      case "submit":
      case "reset":
      case "image":
        return "button";
      case "range":
        return "slider";
      case "number":
        return "spinbutton";
      default:
        return "textbox";
    }
  }
  if (tag === "select") return "combobox";
  if (tag === "textarea") return "textbox";
  if (tag === "button") return "button";
  if (tag === "a") return "link";
  return undefined;
}

function getAccessibleName(el: Element): string | undefined {
  const ariaLabel = el.getAttribute("aria-label");
  if (ariaLabel?.trim()) return ariaLabel.trim().slice(0, 120);

  const labelledBy = el.getAttribute("aria-labelledby");
  if (labelledBy) {
    const root = el.getRootNode() as Document | ShadowRoot;
    const text = labelledBy
      .split(/\s+/)
      .map((id) => root.getElementById?.(id)?.textContent ?? "")
      .join(" ")
      .trim();
    if (text) return text.slice(0, 120);
  }

  if (el instanceof HTMLInputElement || el instanceof HTMLTextAreaElement) {
    const label = el.labels?.[0]?.textContent?.trim();
    if (label) return label.slice(0, 120);
    const placeholder = el.getAttribute("placeholder")?.trim();
    if (placeholder) return placeholder.slice(0, 120);
  }

  if (el instanceof HTMLButtonElement || el instanceof HTMLAnchorElement || el instanceof HTMLElement) {
    const title = el.getAttribute("title")?.trim();
    if (title) return title.slice(0, 120);
    const text = el.textContent?.trim();
    if (text) return text.slice(0, 120);
  }

  const alt = el.getAttribute("alt")?.trim();
  if (alt) return alt.slice(0, 120);

  return undefined;
}

function computeState(el: Element, doc: Document): ElementState | undefined {
  const state: ElementState = {};
  const anyEl = el as HTMLElement;

  if (anyEl.hasAttribute("disabled")) state.disabled = true;
  if (anyEl.getAttribute("aria-disabled") === "true") state.disabled = true;

  const ariaChecked = anyEl.getAttribute("aria-checked");
  if (ariaChecked === "true" || ariaChecked === "false" || ariaChecked === "mixed") {
    state.checked = ariaChecked === "true";
  }
  if (el instanceof HTMLInputElement && (el.type === "checkbox" || el.type === "radio")) {
    state.checked = el.checked;
  }

  const ariaExpanded = anyEl.getAttribute("aria-expanded");
  if (ariaExpanded === "true" || ariaExpanded === "false") {
    state.expanded = ariaExpanded === "true";
  }

  const ariaSelected = anyEl.getAttribute("aria-selected");
  if (ariaSelected === "true" || ariaSelected === "false") {
    state.selected = ariaSelected === "true";
  }

  if (el instanceof HTMLInputElement) state.empty = el.value.length === 0;
  else if (el instanceof HTMLTextAreaElement) state.empty = el.value.length === 0;
  else if (el instanceof HTMLSelectElement) state.empty = el.selectedIndex < 0;

  if (doc.activeElement === el) state.focused = true;

  return Object.keys(state).length > 0 ? state : undefined;
}

function isInteractive(el: Element): boolean {
  const tag = el.tagName.toLowerCase();
  if (["input", "select", "textarea", "button"].includes(tag)) return true;
  if (tag === "a" && el.hasAttribute("href")) return true;
  if (el.hasAttribute("contenteditable")) return true;
  const role = el.getAttribute("role");
  if (
    role &&
    [
      "button",
      "link",
      "checkbox",
      "radio",
      "combobox",
      "menuitem",
      "switch",
      "tab",
      "option",
      "textbox",
      "searchbox",
      "slider",
      "spinbutton",
    ].includes(role)
  ) {
    return true;
  }
  const tabindex = el.getAttribute("tabindex");
  if (tabindex !== null && tabindex !== "-1") return true;
  return false;
}

function collectVisibleText(doc: Document): string[] {
  const selectors = ["h1", "h2", "h3", "h4", "p", "li", "label", "summary", "figcaption", "dt", "dd"];
  const seen = new Set<string>();
  const result: string[] = [];
  for (const sel of selectors) {
    for (const el of Array.from(doc.querySelectorAll(sel))) {
      if (isHidden(el)) continue;
      const text = (el.textContent || "").trim();
      if (!text || text.length > 300) continue;
      const key = text;
      if (seen.has(key)) continue;
      seen.add(key);
      result.push(text);
      if (result.length >= 40) return result;
    }
  }
  return result;
}

/**
 * Build an AccessibleDOMSnapshot from a Document.
 *
 * @param doc the page document (top-level or a frame's document).
 */
export function extractAccessibleDOMSnapshot(
  doc: Document,
  options: ExtractOptions = {},
): AccessibleDOMSnapshot {
  const maxElements = options.maxElements ?? 200;
  const snapshotId = options.snapshotId ?? makeId();

  const url = doc.location?.href ?? "";
  let origin = "";
  try {
    origin = new URL(url).origin;
  } catch {
    origin = "";
  }

  const elements: AccessibleElement[] = [];

  for (const el of Array.from(doc.querySelectorAll(CANDIDATE_SELECTOR))) {
    if (shouldExcludeElement(el)) continue;
    if (elements.length >= maxElements) break;

    const interactive = isInteractive(el);
    const secretKind = classifySecretField(el);
    const role = computeRole(el);
    const accessibleName = getAccessibleName(el);

    // Never serialize a secret-typed input as an interactive control that
    // exposes a value; keep only role/label/state.
    if (secretKind !== "none" && !interactive) continue;

    elements.push({
      id: `el-${elements.length}`,
      tag: el.tagName.toLowerCase(),
      role,
      accessibleName,
      interactive,
      state: computeState(el, doc),
    });
  }

  return {
    schemaVersion: 1,
    snapshotId,
    page: { url, origin, title: doc.title || "" },
    elements,
    visibleText: collectVisibleText(doc),
  };
}
